# Generated by Django 4.2.4 on 2025-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0018_alter_afaregistration_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='paystack_active',
            field=models.BooleanField(default=True),
        ),
    ]
